theme: "hugo-theme-color-your-world"
baseURL: https://www.enigmanauts.com/
languageCode: en-us
title: EnigmaNFTs


menu:
    main:
        - identifier: collections
          name: collections
          url: /collections/
        


